import Doctor from '../models/Doctor';
import logger from '../config/logger';
import {
    ITimeSlot, DayOfWeek, IDoctor, FindDoctorResult, ITimeSlotInput
} from "../types";
import {
    CreateDoctorProfileRequest,
    findDoctorsRequest,
    UpdateDoctorProfileRequest,
    Availability,
    GenerateTimeSlotsRequest,
    UpdateDoctorAvailabilityRequest,
    GetDoctorSlotStatisticsRequest,
} from '../proto/generated/doctor';

export class DoctorService {

    // Helper method to get day of week from date
    private _getDayOfWeek(dateInput: Date | string): DayOfWeek {
        const date = (dateInput instanceof Date) ? dateInput : new Date(dateInput);

        if (isNaN(date.getTime())) {
            throw new Error('Invalid date');
        }

        const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
        return days[date.getDay()] as DayOfWeek;
    }


    // Helper method to find and update slot booking status
    async updateSlotBookingStatus(
        doctorId: string,
        appointmentDate: Date,
        timeSlot: ITimeSlotInput,
        isBooked: boolean
    ) {
        const dayOfWeek = this._getDayOfWeek(appointmentDate);

        const doctor = await Doctor.findById(doctorId);
        if (!doctor) throw new Error('DOctor not found');

        const dayAvailability = doctor.availability.find(avail => avail.day === dayOfWeek);
        if (!dayAvailability) throw new Error('Doctor is not available on this day');

        const slot = dayAvailability.slots.find(s =>
            s.startTime === timeSlot.startTime && s.endTime === timeSlot.endTime
        );

        if (!slot) throw new Error('Time slot not found');

        slot.isBooked = isBooked;
        await doctor.save();
        return slot;
    }

    async getDoctorAvailableSlots(doctorId: string, date: string) {
        try {
            const doctor = await Doctor.findById(doctorId);
            if (!doctor) {
                throw new Error('Doctor not found');
            }

            const requestedDate = new Date(date);
            const dayOfWeek = this._getDayOfWeek(requestedDate);

            const dayAvailability = doctor.availability.find(avail => avail.day === dayOfWeek);
            if (!dayAvailability) {
                throw new Error('Doctor is not available on this day');
            }
            return dayAvailability.slots.filter(slot => !slot.isBooked);
        }
        catch (error) {
            logger.error('Get doctor available slots error:', error);
            throw error;
        }
    }

    private _generateTimeSlots(startTime: string, endTime: string): ITimeSlot[] {
        const slots: ITimeSlot[] = [];

        // Parse start and end times
        const [startHour, startMin] = startTime.split(':').map(Number);
        const [endHour, endMin] = endTime.split(':').map(Number);

        const startTotalMinutes = startHour * 60 + startMin;
        const endTotalMinutes = endHour * 60 + endMin;

        // Generate 30-minute slots
        const gap = Number(process.env.TIMESLOT_GAP) || 30;
        for (let currentMinutes = startTotalMinutes; currentMinutes < endTotalMinutes; currentMinutes += gap) {
            const nextMinutes = currentMinutes + gap;

            // Don't create a slot if it would exceed the end time
            if (nextMinutes > endTotalMinutes) break;

            const currentHour = Math.floor(currentMinutes / 60);
            const currentMin = currentMinutes % 60;
            const nextHour = Math.floor(nextMinutes / 60);
            const nextMinute = nextMinutes % 60;

            const slotStart = `${currentHour.toString().padStart(2, '0')}:${currentMin.toString().padStart(2, '0')}`;
            const slotEnd = `${nextHour.toString().padStart(2, '0')}:${nextMinute.toString().padStart(2, '0')}`;

            slots.push({
                startTime: slotStart,
                endTime: slotEnd,
                isBooked: false
            });
        }

        return slots;
    }

    // Helper method to convert existing time ranges to 30-minute slots
    private _convertToAutoSlots(originalSlots: ITimeSlot[]): ITimeSlot[] {
        const autoGeneratedSlots: ITimeSlot[] = [];

        for (const slot of originalSlots) {
            const generatedSlots = this._generateTimeSlots(slot.startTime, slot.endTime);
            autoGeneratedSlots.push(...generatedSlots);
        }

        return autoGeneratedSlots;
    }

    // Get time slot statistics for a doctor
    private async _getDoctorSlotStatistics(doctorId: string, date?: string) {
        const doctor = await Doctor.findById(doctorId);
        if (!doctor) throw new Error('Doctor not found');

        if (date) {
            // Get statistics for a specific date
            const requestedDate = new Date(date);
            const dayOfWeek = this._getDayOfWeek(requestedDate);
            const dayAvailability = doctor.availability.find(avail => avail.day === dayOfWeek);

            if (!dayAvailability) {
                return {
                    date,
                    dayOfWeek,
                    totalSlots: 0,
                    availableSlots: 0,
                    bookedSlots: 0
                };
            }

            const totalSlots = dayAvailability.slots.length;
            const bookedSlots = dayAvailability.slots.filter(slot => slot.isBooked).length;
            const availableSlots = totalSlots - bookedSlots;

            return {
                date,
                dayOfWeek,
                totalSlots,
                availableSlots,
                bookedSlots
            };
        } else {
            // Get overall statistics for all days
            const weeklyStats = doctor.availability.map(avail => {
                const totalSlots = avail.slots.length;
                const bookedSlots = avail.slots.filter(slot => slot.isBooked).length;
                const availableSlots = totalSlots - bookedSlots;

                return {
                    day: avail.day,
                    totalSlots,
                    availableSlots,
                    bookedSlots
                };
            });

            const overallStats = weeklyStats.reduce((acc, day) => ({
                totalSlots: acc.totalSlots + day.totalSlots,
                availableSlots: acc.availableSlots + day.availableSlots,
                bookedSlots: acc.bookedSlots + day.bookedSlots
            }), { totalSlots: 0, availableSlots: 0, bookedSlots: 0 });

            return {
                weekly: weeklyStats,
                overall: overallStats
            };
        }
    }


    async createDoctorProfile(doctorData: CreateDoctorProfileRequest): Promise<IDoctor> {
        try {
            // Auto-generate 30-minute slots from provided availability
            const processedAvailability = doctorData.availability.map(avail => ({
                day: avail.day,
                slots: this._convertToAutoSlots(avail.slots)
            }));

            const doctor = new Doctor({
                ...doctorData,
                userId: doctorData.userId,
                availability: processedAvailability
            });

            await doctor.save();
            return doctor;
        } catch (error) {
            logger.error('Create Doctor Profile Error: ', error);
            throw error;
        }
    }


    async findDoctors(options: findDoctorsRequest): Promise<FindDoctorResult> {
        const {
            specialization,
            page = 1,
            limit = 10,
            sortBy,
            sortOrder,
        } = options;

        // Build query filters
        const query: any = {};

        // Filter by specialization if provided
        if (specialization) {
            query.specialization = { $regex: specialization, $options: 'i' };
        }

        // Calculate pagination
        const skip = (page - 1) * limit;

        // Build sort object
        const sortObj: any = {};
        sortObj[sortBy] = sortOrder === 'asc' ? 1 : -1;

        try {
            // Execute queries in parallel
            const [doctors, totalCount] = await Promise.all([
                Doctor.find(query)
                    .sort(sortObj)
                    .skip(skip)
                    .limit(limit)
                    .lean(), // Use lean() for better performance
                Doctor.countDocuments(query)
            ]);

            // Calculate pagination metadata
            const totalPages = Math.ceil(totalCount / limit);
            const hasNextPage = page < totalPages;
            const hasPrevPage = page > 1;

            return {
                doctors: doctors,
                totalCount,
                totalPages,
                currentPage: page,
                hasNextPage,
                hasPrevPage
            };
        }
        catch (error) {
            logger.error('Error finding doctors:', error);
            throw error;
        }
    }


    async getDoctorById(doctorId: string): Promise<IDoctor | null> {
        try {
            const doctor = await Doctor.findById(doctorId)
            return doctor;

        } catch (error) {
            logger.error('Get Doctor by ID error:', error);
            throw error;
        }
    }

    async getDoctorByUserId(userId: string): Promise<IDoctor | null> {
        try {
            const doctor = await Doctor.findOne({ userId: userId })
            return doctor;

        } catch (error) {
            logger.error('Get Doctor by User ID error:', error);
            throw error;
        }
    }

    async getDoctorByIds(doctorIds: string[]): Promise<IDoctor[]> {
        try {
            const doctors = await Doctor.find({ _id: { $in: doctorIds } });
            return doctors;

        } catch (error) {
            logger.error('Get Doctor by ID error:', error);
            throw error;
        }
    }


    async updateDoctorProfile(doctorData: UpdateDoctorProfileRequest): Promise<IDoctor | null> {
        try {

            //console.log(JSON.stringify(doctorData));
            // If availability is being updated, auto-generate slots
            if (doctorData.availability) {
                doctorData.availability = doctorData.availability.map((avail: Availability) => ({
                    day: avail.day,
                    slots: this._convertToAutoSlots(avail.slots)
                }));
            }

            const doctor = await Doctor.findOneAndUpdate(
                { userId: doctorData.userId },
                doctorData,
                { new: true, runValidators: true }
            );

            return doctor;
        } catch (error) {
            logger.error('Update user error:', error);
            throw error;
        }
    }


    async generateTimeSlots(data: GenerateTimeSlotsRequest): Promise<ITimeSlot[]> {
        const { startTime, endTime, gap = Number(process.env.TIMESLOT_GAP) || 30 } = data;

        if (!startTime || !endTime) {
            throw new Error('Missing start time and end time when generating time slots');
        }

        // Validate time format
        const timeRegex = /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/;
        if (!timeRegex.test(startTime) || !timeRegex.test(endTime)) {
            throw new Error('Invalid time format');
        }

        // Set gap in environment variable temporarily if provided
        const originalGap = process.env.TIMESLOT_GAP;
        process.env.TIMESLOT_GAP = gap.toString();

        try {
            const slots = this._generateTimeSlots(startTime, endTime);

            // Restore original gap
            if (originalGap) {
                process.env.TIMESLOT_GAP = originalGap;
            } else {
                delete process.env.TIMESLOT_GAP;
            }

            return slots;
        } catch (error) {
            logger.error('Error generating time slots:', error);
            throw error;
        }
    }

    // Helper to process doctor availability and auto-generate slots
    private async _processAndSaveDoctorAvailability(doctorId: string, availability: any[]) {
        const doctor = await Doctor.findById(doctorId);
        if (!doctor) throw new Error('Doctor not found');

        // Process each availability entry
        const processedAvailability = availability.map(avail => ({
            day: avail.day,
            slots: this._convertToAutoSlots(avail.slots)
        }));

        doctor.availability = processedAvailability;
        await doctor.save();

        return doctor;
    }

    async updateDoctorAvailability(data: UpdateDoctorAvailabilityRequest): Promise<IDoctor | null> {
        try {
            const { userId, availability } = data;

            if (!availability || !Array.isArray(availability)) {
                throw new Error('Missing inputs when updating doctor availability');
            }

            const doctor = await Doctor.findOne({ userId: userId });
            if (!doctor)
                throw new Error('User is not a doctor');

            const doctorUpdated = await this._processAndSaveDoctorAvailability(doctor._id, availability);
            return doctorUpdated;
        } catch (error) {
            logger.error('Update doctor availability error:', error);
            throw error;
        }
    }


    async getDoctorSlotStatistics(data: GetDoctorSlotStatisticsRequest) {
        try {
            const { doctorId, date } = data;
            let statistics;
            if (date) {
                statistics = await this._getDoctorSlotStatistics(
                    doctorId,
                    date as string
                );
            }
            else {
                statistics = await this._getDoctorSlotStatistics(
                    doctorId
                );
            }

            return statistics;
        } catch (error) {
            logger.error('Get Doctor Slot Statistics Error:', error);
            throw error;
        }
    }

    async regenerateDoctorSlots(doctorId: string, gap = 30) {
        try {
            const doctor = await Doctor.findById(doctorId);
            if (!doctor) {
                throw new Error('Doctor not found when regenerating time slots.');
            }

            // Set gap temporarily
            const originalGap = process.env.TIMESLOT_GAP;
            process.env.TIMESLOT_GAP = gap.toString();

            // Recreate slots with new gap, preserving booking status by time matching
            const updatedAvailability = doctor.availability.map(avail => {
                // Group existing slots by their original time ranges
                const timeRanges: { startTime: string; endTime: string; bookedSlots: string[] }[] = [];

                // Find consecutive slots to rebuild original ranges
                const sortedSlots = avail.slots.sort((a, b) => a.startTime.localeCompare(b.startTime));

                if (sortedSlots.length > 0) {
                    let currentRange = {
                        startTime: sortedSlots[0].startTime,
                        endTime: sortedSlots[0].endTime,
                        bookedSlots: sortedSlots[0].isBooked ? [sortedSlots[0].startTime] : []
                    };

                    for (let i = 1; i < sortedSlots.length; i++) {
                        const slot = sortedSlots[i];

                        // If current slot starts where previous ended, extend the range
                        if (slot.startTime === currentRange.endTime) {
                            currentRange.endTime = slot.endTime;
                            if (slot.isBooked) {
                                currentRange.bookedSlots.push(slot.startTime);
                            }
                        } else {
                            // Save current range and start new one
                            timeRanges.push(currentRange);
                            currentRange = {
                                startTime: slot.startTime,
                                endTime: slot.endTime,
                                bookedSlots: slot.isBooked ? [slot.startTime] : []
                            };
                        }
                    }
                    timeRanges.push(currentRange);
                }

                // Generate new slots from time ranges
                const newSlots: ITimeSlot[] = [];
                for (const range of timeRanges) {
                    const generatedSlots = this._generateTimeSlots(range.startTime, range.endTime);

                    // Restore booking status for slots that were previously booked
                    generatedSlots.forEach(slot => {
                        if (range.bookedSlots.includes(slot.startTime)) {
                            slot.isBooked = true;
                        }
                    });

                    newSlots.push(...generatedSlots);
                }

                return {
                    day: avail.day,
                    slots: newSlots
                };
            });

            doctor.availability = updatedAvailability;
            await doctor.save();

            // Restore original gap
            if (originalGap) {
                process.env.TIMESLOT_GAP = originalGap;
            } else {
                delete process.env.TIMESLOT_GAP;
            }

            return doctor;
        } catch (error) {
            logger.error('Regenerating Doctor Time Slots Error:', error);
            throw error;
        }
    }

    /**
 * Delete one or multiple doctors by ID(s)
 */
    async deleteDoctors(ids: string | string[]): Promise<boolean> {
        try {
            if (Array.isArray(ids)) {
                const result = await Doctor.deleteMany({ _id: { $in: ids } });
                return result.deletedCount === ids.length;
            } else {
                const result = await Doctor.findByIdAndDelete(ids);
                return !!result;
            }
        } catch (error) {
            logger.error('Delete Doctor error:', error);
            throw error;
        }
    }
}

export const doctorService = new DoctorService();
export default doctorService;