syntax = "proto3";

package prescriptionPackage;

option java_multiple_files = true;
option java_package = "uni.hcmus.medicineservice.grpc";
option java_outer_classname = "PrescriptionServiceProto";

import "MedicineService.proto";
import "google/protobuf/empty.proto";

service PrescriptionService {
  rpc GetAllPrescriptions (Empty) returns (PrescriptionListResponse);
  rpc GetPrescriptionById (PrescriptionIdRequest) returns (PrescriptionResponse);
  rpc CreatePrescription (CreatePrescriptionRequest) returns (PrescriptionResponse);
  rpc UpdatePrescription (UpdatePrescriptionRequest) returns (PrescriptionResponse);
  rpc DeletePrescription (PrescriptionIdRequest) returns (Empty);
}

message PrescriptionIdRequest {
  string prescription_id = 1;
}

message PrescriptionResponse {
  string prescription_id = 1;
  string medical_record_id = 2;
  double total_cost = 3;
  string status = 4;
  bool is_paid = 5;
  string created_at = 6;
  string updated_at = 7;
  repeated PrescriptionItemResponse items = 8;
}

message PrescriptionItemResponse {
  string prescription_item_id = 1;
  MedicineResponse medicine = 2;
  int32 quantity = 3;
  string dosage_instruction = 4;
  double total_cost = 5;
}

message PrescriptionListResponse {
  repeated PrescriptionResponse prescriptions = 1;
}

message CreatePrescriptionRequest {
  string medical_record_id = 1;
  repeated CreatePrescriptionItemRequest items = 2;
}

message CreatePrescriptionItemRequest {
  string medicine_id = 1;
  int32 quantity = 2;
  string dosage_instruction = 3;
}

message UpdatePrescriptionRequest {
  string prescription_id = 1;
  string medical_record_id = 2;
  repeated UpdatePrescriptionItemRequest items = 3;
}

message UpdatePrescriptionItemRequest {
  string prescription_item_id = 1;
  string medicine_id = 2;
  int32 quantity = 3;
  string dosage_instruction = 4;
}