services:
  notification_services:
    build: .
    ports:
      - "3006:3006"
    env_file:
      - ./.env
    container_name: notification-services
    depends_on:
      - rabbitmq-notification
      - mysql-notification

  rabbitmq-notification:
    image: rabbitmq:3-management
    ports:
      - "5674:5672"     # RabbitMQ main port
      - "15674:15672"   # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql-notification:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logs
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d # Mount the initialization scripts