# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0b\x61ppointment\"\x9e\x01\n\x12\x41ppointmentRequest\x12\x13\n\x0bpatientName\x18\x01 \x01(\t\x12\x14\n\x0cpatientEmail\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x11\n\tstartTime\x18\x04 \x01(\t\x12\x0f\n\x07\x65ndTime\x18\x05 \x01(\t\x12\x12\n\ndoctorName\x18\x06 \x01(\t\x12\x17\n\x0f\x63onsultationFee\x18\x07 \x01(\x05\"0\n\x18PrescriptionReadyRequest\x12\x14\n\x0cpatientEmail\x18\x01 \x01(\t\"7\n\x13\x41ppointmentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc9\x01\n\x12\x41ppointmentService\x12Q\n\x0cSendReminder\x12\x1f.appointment.AppointmentRequest\x1a .appointment.AppointmentResponse\x12`\n\x15SendPrescriptionReady\x12%.appointment.PrescriptionReadyRequest\x1a .appointment.AppointmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPOINTMENTREQUEST']._serialized_start=36
  _globals['_APPOINTMENTREQUEST']._serialized_end=194
  _globals['_PRESCRIPTIONREADYREQUEST']._serialized_start=196
  _globals['_PRESCRIPTIONREADYREQUEST']._serialized_end=244
  _globals['_APPOINTMENTRESPONSE']._serialized_start=246
  _globals['_APPOINTMENTRESPONSE']._serialized_end=301
  _globals['_APPOINTMENTSERVICE']._serialized_start=304
  _globals['_APPOINTMENTSERVICE']._serialized_end=505
# @@protoc_insertion_point(module_scope)
