# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import notification_pb2 as notification__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in notification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AppointmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendReminder = channel.unary_unary(
                '/appointment.AppointmentService/SendReminder',
                request_serializer=notification__pb2.AppointmentRequest.SerializeToString,
                response_deserializer=notification__pb2.AppointmentResponse.FromString,
                _registered_method=True)
        self.SendPrescriptionReady = channel.unary_unary(
                '/appointment.AppointmentService/SendPrescriptionReady',
                request_serializer=notification__pb2.PrescriptionReadyRequest.SerializeToString,
                response_deserializer=notification__pb2.AppointmentResponse.FromString,
                _registered_method=True)
        self.AcceptAppointment = channel.unary_unary(
                '/appointment.AppointmentService/AcceptAppointment',
                request_serializer=notification__pb2.AcceptAppointmentRequest.SerializeToString,
                response_deserializer=notification__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.AddUser = channel.unary_unary(
                '/appointment.AppointmentService/AddUser',
                request_serializer=notification__pb2.AddUserRequest.SerializeToString,
                response_deserializer=notification__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.BookAppointment = channel.unary_unary(
                '/appointment.AppointmentService/BookAppointment',
                request_serializer=notification__pb2.AnalysisAppointmentRequest.SerializeToString,
                response_deserializer=notification__pb2.AnalysisAppointmentResponse.FromString,
                _registered_method=True)
        self.GetUpcomingConfirmedAppointments = channel.unary_unary(
                '/appointment.AppointmentService/GetUpcomingConfirmedAppointments',
                request_serializer=notification__pb2.Empty.SerializeToString,
                response_deserializer=notification__pb2.GetUpcomingConfirmedAppointmentsResponse.FromString,
                _registered_method=True)


class AppointmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendReminder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPrescriptionReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpcomingConfirmedAppointments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppointmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendReminder': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReminder,
                    request_deserializer=notification__pb2.AppointmentRequest.FromString,
                    response_serializer=notification__pb2.AppointmentResponse.SerializeToString,
            ),
            'SendPrescriptionReady': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPrescriptionReady,
                    request_deserializer=notification__pb2.PrescriptionReadyRequest.FromString,
                    response_serializer=notification__pb2.AppointmentResponse.SerializeToString,
            ),
            'AcceptAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptAppointment,
                    request_deserializer=notification__pb2.AcceptAppointmentRequest.FromString,
                    response_serializer=notification__pb2.GenericResponse.SerializeToString,
            ),
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=notification__pb2.AddUserRequest.FromString,
                    response_serializer=notification__pb2.GenericResponse.SerializeToString,
            ),
            'BookAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.BookAppointment,
                    request_deserializer=notification__pb2.AnalysisAppointmentRequest.FromString,
                    response_serializer=notification__pb2.AnalysisAppointmentResponse.SerializeToString,
            ),
            'GetUpcomingConfirmedAppointments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpcomingConfirmedAppointments,
                    request_deserializer=notification__pb2.Empty.FromString,
                    response_serializer=notification__pb2.GetUpcomingConfirmedAppointmentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'appointment.AppointmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('appointment.AppointmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppointmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendReminder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appointment.AppointmentService/SendReminder',
            notification__pb2.AppointmentRequest.SerializeToString,
            notification__pb2.AppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPrescriptionReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appointment.AppointmentService/SendPrescriptionReady',
            notification__pb2.PrescriptionReadyRequest.SerializeToString,
            notification__pb2.AppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appointment.AppointmentService/AcceptAppointment',
            notification__pb2.AcceptAppointmentRequest.SerializeToString,
            notification__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appointment.AppointmentService/AddUser',
            notification__pb2.AddUserRequest.SerializeToString,
            notification__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BookAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appointment.AppointmentService/BookAppointment',
            notification__pb2.AnalysisAppointmentRequest.SerializeToString,
            notification__pb2.AnalysisAppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUpcomingConfirmedAppointments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appointment.AppointmentService/GetUpcomingConfirmedAppointments',
            notification__pb2.Empty.SerializeToString,
            notification__pb2.GetUpcomingConfirmedAppointmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
