[supervisord]
nodaemon=true

[program:server]
command=python server_new.py
directory=/app
autostart=true
autorestart=true

[program:worker]
command=python email_worker.py
directory=/app
autostart=true
autorestart=true