# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analysis_pb2 as analysis__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookAppointment = channel.unary_unary(
                '/analysis.AnalysisService/BookAppointment',
                request_serializer=analysis__pb2.AnalysisAppointmentRequest.SerializeToString,
                response_deserializer=analysis__pb2.AnalysisAppointmentResponse.FromString,
                _registered_method=True)
        self.BookPrescription = channel.unary_unary(
                '/analysis.AnalysisService/BookPrescription',
                request_serializer=analysis__pb2.PrescriptionRequest.SerializeToString,
                response_deserializer=analysis__pb2.PrescriptionResponse.FromString,
                _registered_method=True)
        self.UpdatePrescriptionStatus = channel.unary_unary(
                '/analysis.AnalysisService/UpdatePrescriptionStatus',
                request_serializer=analysis__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=analysis__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.MarkPrescriptionPaid = channel.unary_unary(
                '/analysis.AnalysisService/MarkPrescriptionPaid',
                request_serializer=analysis__pb2.UpdatePaidRequest.SerializeToString,
                response_deserializer=analysis__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.GetPatientStatistics = channel.unary_unary(
                '/analysis.AnalysisService/GetPatientStatistics',
                request_serializer=analysis__pb2.PatientStatisticsRequest.SerializeToString,
                response_deserializer=analysis__pb2.PatientStatisticsResponse.FromString,
                _registered_method=True)
        self.GetPrescriptionStatistics = channel.unary_unary(
                '/analysis.AnalysisService/GetPrescriptionStatistics',
                request_serializer=analysis__pb2.PrescriptionStatisticsRequest.SerializeToString,
                response_deserializer=analysis__pb2.PrescriptionStatisticsResponse.FromString,
                _registered_method=True)
        self.AcceptAppointment = channel.unary_unary(
                '/analysis.AnalysisService/AcceptAppointment',
                request_serializer=analysis__pb2.AcceptAppointmentRequest.SerializeToString,
                response_deserializer=analysis__pb2.GenericResponse.FromString,
                _registered_method=True)


class AnalysisServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BookAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookPrescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePrescriptionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkPrescriptionPaid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrescriptionStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BookAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.BookAppointment,
                    request_deserializer=analysis__pb2.AnalysisAppointmentRequest.FromString,
                    response_serializer=analysis__pb2.AnalysisAppointmentResponse.SerializeToString,
            ),
            'BookPrescription': grpc.unary_unary_rpc_method_handler(
                    servicer.BookPrescription,
                    request_deserializer=analysis__pb2.PrescriptionRequest.FromString,
                    response_serializer=analysis__pb2.PrescriptionResponse.SerializeToString,
            ),
            'UpdatePrescriptionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePrescriptionStatus,
                    request_deserializer=analysis__pb2.UpdateStatusRequest.FromString,
                    response_serializer=analysis__pb2.GenericResponse.SerializeToString,
            ),
            'MarkPrescriptionPaid': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkPrescriptionPaid,
                    request_deserializer=analysis__pb2.UpdatePaidRequest.FromString,
                    response_serializer=analysis__pb2.GenericResponse.SerializeToString,
            ),
            'GetPatientStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientStatistics,
                    request_deserializer=analysis__pb2.PatientStatisticsRequest.FromString,
                    response_serializer=analysis__pb2.PatientStatisticsResponse.SerializeToString,
            ),
            'GetPrescriptionStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrescriptionStatistics,
                    request_deserializer=analysis__pb2.PrescriptionStatisticsRequest.FromString,
                    response_serializer=analysis__pb2.PrescriptionStatisticsResponse.SerializeToString,
            ),
            'AcceptAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptAppointment,
                    request_deserializer=analysis__pb2.AcceptAppointmentRequest.FromString,
                    response_serializer=analysis__pb2.GenericResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analysis.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analysis.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BookAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/BookAppointment',
            analysis__pb2.AnalysisAppointmentRequest.SerializeToString,
            analysis__pb2.AnalysisAppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BookPrescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/BookPrescription',
            analysis__pb2.PrescriptionRequest.SerializeToString,
            analysis__pb2.PrescriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePrescriptionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/UpdatePrescriptionStatus',
            analysis__pb2.UpdateStatusRequest.SerializeToString,
            analysis__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkPrescriptionPaid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/MarkPrescriptionPaid',
            analysis__pb2.UpdatePaidRequest.SerializeToString,
            analysis__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatientStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetPatientStatistics',
            analysis__pb2.PatientStatisticsRequest.SerializeToString,
            analysis__pb2.PatientStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrescriptionStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/GetPrescriptionStatistics',
            analysis__pb2.PrescriptionStatisticsRequest.SerializeToString,
            analysis__pb2.PrescriptionStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnalysisService/AcceptAppointment',
            analysis__pb2.AcceptAppointmentRequest.SerializeToString,
            analysis__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
