services:
  analysis_services:
    build: .
    ports:
      - "3005:3005"
    env_file:
      - ./.env
    container_name: analysis-services
    depends_on:
      - rabbitmq-analysis
      - mysql-analysis

  rabbitmq-analysis:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"     # RabbitMQ main port
      - "15673:15672"   # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql-analysis:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointment_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d # Mount the initialization scripts