[supervisord]
nodaemon=true

[program:server]
command=python grpc_server.py
directory=/app
autostart=true
autorestart=true

[program:appointment_worker]
command=python consumer.py
directory=/app
autostart=true
autorestart=true

[program:appointment_update_worker]
command=python consumer_update.py
directory=/app
autostart=true
autorestart=true

[program:prescription_worker]
command=python consumer_prescription.py
directory=/app
autostart=true
autorestart=true

[program:prescription_update_worker]
command=python consumer_prescription_update.py
directory=/app
autostart=true
autorestart=true