<?php
return [
    'base_url' => getenv('API_BASE_URL') ?: 'http://gateway:3000',
    'timeout' => 30,
    'headers' => [
        'Content-Type' => 'application/json',
        'Accept' => 'application/json'
    ],
    'endpoints' => [
        'login' => '/api/user/login',
        'register' => '/api/user/register',
        'logout' => '/api/user/logout',
        'users' => '/api/user',
        'posts' => '/posts',
        'doctors' => '/api/doctors/',
        'doctor_get_id' => '/api/doctor/GetDoctorById',
        'doctor_get_userId' => '/api/doctor/GetDoctorByUserId',
        'update_doctor' => '/doctors/update',
        'update_doctor_availability' => '/doctors/updateAvailability',
        'appointment_get_id' => 'Appointments',
        'patient_info' => '/api/patient',
        'medicine' => '/api/medicine',
        'medicine_get_all' => '/api/medicine/GetAllMedicines',
        'medicine_get_by_id' => '/api/medicine/GetMedicineById',
        'medicine_create' => '/api/medicine/CreateMedicine',
        'medicine_update' => '/api/medicine/UpdateMedicine',
        'medicine_delete' => '/api/medicine/DeleteMedicine',
        'medicine_restore' => '/api/medicine/RestoreMedicine',
        'prescription' => '/api/prescription',
        'prescription_get_all' => '/api/prescription/GetAllPrescriptions',
        'prescription_get_by_id' => '/api/prescription/GetPrescriptionById',
        'prescription_create' => '/api/prescription/CreatePrescription',
        'prescription_update' => '/api/prescription/UpdatePrescription',
        'prescription_delete' => '/api/prescription/DeletePrescription',
        'prescription_restore' => '/api/prescription/RestorePrescription',

        'notification_get_upcoming_appointment' => '/api/notification/GetUpcomingConfirmedAppointments',
        'notification_send_reminder' => '/api/notification/SendReminder',
        'notification_send_prescription_ready' => '/api/notification/SendPrescriptionReady',
        'notification_accept_appointment' => '/api/notification/AcceptAppointment',
        'notification_book_appointment' => '/api/notification/BookAppointment',
        'notification_add_user' => '/api/notification/AddUser',

        'analysis_accept_appointment' => '/api/analysis/AcceptAppointment',
        'analysis_book_appointment' => '/api/analysis/BookAppointment',
        'analysis_book_prescription' => '/api/analysis/BookPrescription',
        'analysis_update_prescription_status' => '/api/analysis/UpdatePrescriptionStatus',
        'analysis_mark_prescription_paid' => '/api/analysis/MarkPrescriptionPaid',
        'analysis_get_prescription_statistics' => '/api/analysis/GetPrescriptionStatistics',
        'analysis_get_patient_statistics' => '/api/analysis/GetPatientStatistics',
    ]
];
