spring.application.name=email-service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pdai.congviec@gmail.com
spring.mail.password=ixouorzcsxgrsdeu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
