# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import patient_pb2 as patient__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in patient_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PatientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVisit = channel.unary_unary(
                '/patientPackage.PatientService/GetVisit',
                request_serializer=patient__pb2.GetVisitRequest.SerializeToString,
                response_deserializer=patient__pb2.GetVisitResponse.FromString,
                _registered_method=True)
        self.ListVisits = channel.unary_unary(
                '/patientPackage.PatientService/ListVisits',
                request_serializer=patient__pb2.ListVisitsRequest.SerializeToString,
                response_deserializer=patient__pb2.ListVisitsResponse.FromString,
                _registered_method=True)
        self.CreateVisit = channel.unary_unary(
                '/patientPackage.PatientService/CreateVisit',
                request_serializer=patient__pb2.CreateVisitRequest.SerializeToString,
                response_deserializer=patient__pb2.CreateVisitResponse.FromString,
                _registered_method=True)
        self.UpdateVisit = channel.unary_unary(
                '/patientPackage.PatientService/UpdateVisit',
                request_serializer=patient__pb2.UpdateVisitRequest.SerializeToString,
                response_deserializer=patient__pb2.CreateVisitResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/patientPackage.PatientService/Check',
                request_serializer=patient__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=patient__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PatientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVisit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVisits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVisit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVisit(self, request, context):
        """dùng lại response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVisit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVisit,
                    request_deserializer=patient__pb2.GetVisitRequest.FromString,
                    response_serializer=patient__pb2.GetVisitResponse.SerializeToString,
            ),
            'ListVisits': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVisits,
                    request_deserializer=patient__pb2.ListVisitsRequest.FromString,
                    response_serializer=patient__pb2.ListVisitsResponse.SerializeToString,
            ),
            'CreateVisit': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVisit,
                    request_deserializer=patient__pb2.CreateVisitRequest.FromString,
                    response_serializer=patient__pb2.CreateVisitResponse.SerializeToString,
            ),
            'UpdateVisit': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVisit,
                    request_deserializer=patient__pb2.UpdateVisitRequest.FromString,
                    response_serializer=patient__pb2.CreateVisitResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=patient__pb2.HealthCheckRequest.FromString,
                    response_serializer=patient__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'patientPackage.PatientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('patientPackage.PatientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVisit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientPackage.PatientService/GetVisit',
            patient__pb2.GetVisitRequest.SerializeToString,
            patient__pb2.GetVisitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVisits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientPackage.PatientService/ListVisits',
            patient__pb2.ListVisitsRequest.SerializeToString,
            patient__pb2.ListVisitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVisit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientPackage.PatientService/CreateVisit',
            patient__pb2.CreateVisitRequest.SerializeToString,
            patient__pb2.CreateVisitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVisit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientPackage.PatientService/UpdateVisit',
            patient__pb2.UpdateVisitRequest.SerializeToString,
            patient__pb2.CreateVisitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patientPackage.PatientService/Check',
            patient__pb2.HealthCheckRequest.SerializeToString,
            patient__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
