# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app import patient_pb2 as patient__pb2


GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in patient_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PatientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVisitHistory = channel.unary_unary(
                '/patient.PatientService/GetVisitHistory',
                request_serializer=patient__pb2.GetVisitHistoryRequest.SerializeToString,
                response_deserializer=patient__pb2.VisitHistoryResponse.FromString,
                _registered_method=True)
        self.GetPatientInfo = channel.unary_unary(
                '/patient.PatientService/GetPatientInfo',
                request_serializer=patient__pb2.GetPatientInfoRequest.SerializeToString,
                response_deserializer=patient__pb2.PatientInfoResponse.FromString,
                _registered_method=True)


class PatientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVisitHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVisitHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVisitHistory,
                    request_deserializer=patient__pb2.GetVisitHistoryRequest.FromString,
                    response_serializer=patient__pb2.VisitHistoryResponse.SerializeToString,
            ),
            'GetPatientInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientInfo,
                    request_deserializer=patient__pb2.GetPatientInfoRequest.FromString,
                    response_serializer=patient__pb2.PatientInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'patient.PatientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('patient.PatientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVisitHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/GetVisitHistory',
            patient__pb2.GetVisitHistoryRequest.SerializeToString,
            patient__pb2.VisitHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatientInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientService/GetPatientInfo',
            patient__pb2.GetPatientInfoRequest.SerializeToString,
            patient__pb2.PatientInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
