# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: patient.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'patient.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpatient.proto\x12\x07patient\",\n\x16GetVisitHistoryRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\"n\n\x05Visit\x12\x10\n\x08visit_id\x18\x01 \x01(\t\x12\x12\n\ndepartment\x18\x02 \x01(\t\x12\x12\n\nvisit_date\x18\x03 \x01(\t\x12\x18\n\x10reason_for_visit\x18\x04 \x01(\t\x12\x11\n\tdiagnosis\x18\x05 \x01(\t\"6\n\x14VisitHistoryResponse\x12\x1e\n\x06visits\x18\x01 \x03(\x0b\x32\x0e.patient.Visit\"+\n\x15GetPatientInfoRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\"U\n\x13PatientInfoResponse\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t2\xb3\x01\n\x0ePatientService\x12Q\n\x0fGetVisitHistory\x12\x1f.patient.GetVisitHistoryRequest\x1a\x1d.patient.VisitHistoryResponse\x12N\n\x0eGetPatientInfo\x12\x1e.patient.GetPatientInfoRequest\x1a\x1c.patient.PatientInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'patient_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETVISITHISTORYREQUEST']._serialized_start=26
  _globals['_GETVISITHISTORYREQUEST']._serialized_end=70
  _globals['_VISIT']._serialized_start=72
  _globals['_VISIT']._serialized_end=182
  _globals['_VISITHISTORYRESPONSE']._serialized_start=184
  _globals['_VISITHISTORYRESPONSE']._serialized_end=238
  _globals['_GETPATIENTINFOREQUEST']._serialized_start=240
  _globals['_GETPATIENTINFOREQUEST']._serialized_end=283
  _globals['_PATIENTINFORESPONSE']._serialized_start=285
  _globals['_PATIENTINFORESPONSE']._serialized_end=370
  _globals['_PATIENTSERVICE']._serialized_start=373
  _globals['_PATIENTSERVICE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
