services:
  gateway:
    build:
      context: ./services/gateway
    ports:
      - "3000:3000"
    depends_on:
      - patient-services
      - medicine-services
      # - appointment-services
      # - doctor-services
    networks:
      - internal

  patient-services:
    build:
      context: ./services/patient_services
    expose:
      - "3001"
    networks:
      - internal

  # appointment-services:
  #   build:
  #     context: ./services/appointment_services
  #  expose:
  #     - "3002"
  #   networks:
  #     - internal

  # doctor-services:
  #   build:
  #     context: ./services/doctor_services
  #  expose:
  #     - "3003"
  #   networks:
  #     - internal

  medicine-services:
    build:
      context: ./services/medicine_services
    expose:
      - "3004"
    networks:
      - internal

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - gateway
  #   networks:
  #     - internal

networks:
  internal:
    driver: bridge
